---
# tasks file for rsyslog

- name: Enable rsyslog.conf is correct
  ansible.builtin.copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure rsyslog is starte and enabled
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true


