---
- name: Check security baseline
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure auditd daemon is started and enabled
      ansible.builtin.service:
        name: auditd
        state: started
        enabled: true
      check_mode: true
      register: auditd

    - name: Ensure rsyslog is starte and enabled
      ansible.builtin.service:
        name: rsyslog
        state: started
        enabled: true
      check_mode: true
      register: rsyslog

    - name: Set sysctl parameters
      ansible.posix.sysctl:
        name: net.ipv4.tcp_syncookies
        value: 1
        state: present
      check_mode: true
      register: sysctl

    - name: Enforce standard if checks fails
      ansible.builtin.include_tasks:
        file: enforce-baseline.yml
      when:
        - sysctl.changed is true or
          rsyslog.changed is true or
          auditd.changed is true
