---
- name: Validate input
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure ansible_eda.event.description refers to a valid inventory host
      assert:
        that:
          - "ansible_eda.event.description | split(' ') | regex_search('node=(.+).sudo.net', '\\1') | first }}.sudo.net" in groups['all']
        fail_msg: "Host {{ ansible_eda.event.description | split(' ') | regex_search('node=(.+).sudo.net', '\\1') | first }}.sudo.net is NOT in the inventory!"
        success_msg: "Host {{ ansible_eda.event.description | split(' ') | regex_search('node=(.+).sudo.net', '\\1') | first }}.sudo.net is present in the inventory."

- name: Apply security baseline
  hosts: "{{ ansible_eda.event.description | split(' ') | regex_search('node=(.+).sudo.net', '\\1') | first }}.sudo.net"
  become: true
  tasks:
    - name: Auditd rule violation information
      ansible.builtin.debug:
        msg: "audit.log information: {{ ansible_eda.event.description }}"

    - name: Include hosts role
      ansible.builtin.include_role:
        name: hosts

    - name: Include rpmbaseline role
      ansible.builtin.include_role:
        name: rpmbaseline

    - name: Include audit role
      ansible.builtin.include_role:
        name: audit

    - name: Include rsyslog role
      ansible.builtin.include_role:
        name: rsyslog

    - name: Include sysctl role
      ansible.builtin.include_role:
        name: sysctl
