---
- name: Apply security baseline
  hosts: "{{ ansible_eda.event.body.hostname }}"
  become: true
  tasks:
    - name: Auditd rule violation information
      ansible.builtin.debug:
        msg: "audit.log information: {{ ansible_eda.event.body.message }}"

    - name: Include hosts role
      ansible.builtin.include_role:
        name: hosts

    - name: Include rpmbaseline role
      ansible.builtin.include_role:
        name: rpmbaseline

    - name: Include audit role
      ansible.builtin.include_role:
        name: audit

    - name: Include rsyslog role
      ansible.builtin.include_role:
        name: rsyslog

    - name: Include sysctl role
      ansible.builtin.include_role:
        name: sysctl
