---
- name: Apply security baseline
  hosts: "{{ ansible_eda.event.body.hostname }}"
  become: true
  tasks:
    - name: Include /etc/hosts role
      ansible.builtin.include_role:
        name: hosts
