---
- name: Apply security baseline
  hosts: "{{ ansible_eda.event.description | split(' ') | regex_search('node=(.+).sudo.net', '\\1') | first }}.sudo.net"
  become: true
  tasks:
    - name: Auditd rule violation information
      ansible.builtin.debug:
        msg: "audit.log information: {{ ansible_eda.event.description }}"

    - name: Include hosts role
      ansible.builtin.include_role:
        name: hosts

    - name: Include rpmbaseline role
      ansible.builtin.include_role:
        name: rpmbaseline

    - name: Include audit role
      ansible.builtin.include_role:
        name: audit

    - name: Include rsyslog role
      ansible.builtin.include_role:
        name: rsyslog

    - name: Include sysctl role
      ansible.builtin.include_role:
        name: sysctl

    - name: close incidents from list
      servicenow.itsm.incident:
        state: closed
        number: "{{ ansible_eda.event.number }}"
        close_code: "Solved (Permanently)"
        close_notes: "Security baseline breach automatically remediated by Ansible Automation Platform"
        other:
          active: false
        instance:
          host: "https://{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      delegate_to: localhost
