---
- name: Validate input
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure ansible_eda.event.description refers to a valid inventory host
      assert:
        that:
          - ansible_eda.event.description | regex_search('node=([^ ]+)', '\\1') in groups['all']
        fail_msg: "Host '{{ {{ ansible_eda.event.description | regex_search('node=([^ ]+)', '\\1') }} }}' is NOT in the inventory!"
        success_msg: "Host '{{ {{ ansible_eda.event.description | regex_search('node=([^ ]+)', '\\1') }} }}' is present in the inventory."
      delegate_to: localhost


- name: Apply security baseline
  hosts: "{{ ansible_eda.event.description | regex_search('node=([^ ]+)', '\\1') }}"
  become: true
  tasks:
    - name: Create change request for resolving a problem
      servicenow.itsm.change_request:
        instance:
          host: "{{ SNOW_INSTANCE }}"
        state: new
        type: standard
        short_description: "From incident: {{ ansible_eda.event.number }}: Reapply security baseline for {{ ansible_eda.event.description | regex_search('node=([^ ]+)', '\\1') }}"
        description: "Ansible Automation Platform will automatically reapply the security baseline"
        on_hold: false
        instance:
          host: "{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      delegate_to: localhost
      register: change

    - name: Auditd rule violation information
      ansible.builtin.debug:
        msg: "audit.log information: {{ ansible_eda.event.description }}"

    - name: Include hosts role
      ansible.builtin.include_role:
        name: hosts

    - name: Include rpmbaseline role
      ansible.builtin.include_role:
        name: rpmbaseline

    - name: Include audit role
      ansible.builtin.include_role:
        name: audit

    - name: Include rsyslog role
      ansible.builtin.include_role:
        name: rsyslog

    - name: Include sysctl role
      ansible.builtin.include_role:
        name: sysctl

    - name: Close change request
      servicenow.itsm.change_request:
        state: closed
        close_code: "successful"
        close_notes: "Resolved issue: {{ ansible_eda.event.description }}"
        assignment_group: Change Management
        number: "{{ change.record.number }}"
        instance:
          host: "{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      delegate_to: localhost

    - name: Close incident
      servicenow.itsm.incident:
        state: closed
        number: "{{ ansible_eda.event.number }}"
        close_code: "Solved (Permanently)"
        close_notes: "Change {{ change.record.number }} closed. Security baseline breach automatically remediated by Ansible Automation Platform"
        other:
          active: false
        instance:
          host: "{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      delegate_to: localhost
