---
- name: Apply security baseline
  hosts: "{{ ansible_eda.event.description | regex_search('node=([^ ]+)', '\\1') }}"
  become: true
  tasks:
    - name: Create change request for resolving a problem
      servicenow.itsm.change_request:
        instance:
          host: "{{ SNOW_INSTANCE }}"
        state: new
        type: standard
        short_description: "Reapply security baseline for {{ ansible_eda.event.description | regex_search('node=([^ ]+)', '\\1') }}"
        description: "Ansible Automation Platform will automatically reapply the security baseline"
        on_hold: false
        other:
          incident_id: "{{ ansible_eda.event.number }}"
        instance:
          host: "{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      delegate_to: localhost
      register: change

    - name: Auditd rule violation information
      ansible.builtin.debug:
        msg: "audit.log information: {{ ansible_eda.event.description }}"

    - name: Include hosts role
      ansible.builtin.include_role:
        name: hosts

    - name: Include rpmbaseline role
      ansible.builtin.include_role:
        name: rpmbaseline

    - name: Include audit role
      ansible.builtin.include_role:
        name: audit

    - name: Include rsyslog role
      ansible.builtin.include_role:
        name: rsyslog

    - name: Include sysctl role
      ansible.builtin.include_role:
        name: sysctl

    - name: Close change request
      servicenow.itsm.change_request:
        state: closed
        close_code: "successful"
        close_notes: "Resolved issue: {{ ansible_eda.event.description }}"
        assignment_group: Change Management
        number: "{{ change.record.number }}"
        instance:
          host: "{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      delegate_to: localhost

    - name: Close incident
      servicenow.itsm.incident:
        state: closed
        number: "{{ ansible_eda.event.number }}"
        close_code: "Solved (Permanently)"
        close_notes: "Security baseline breach automatically remediated by Ansible Automation Platform"
        other:
          change_id: "{{ change.record.number }}"
          active: false
        instance:
          host: "{{ SNOW_INSTANCE }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      delegate_to: localhost
