---
# tasks file for sysctl

- name: Ensure /etc/sysctl.conf configuration is correct
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Ensure /etc/sysctl.d/zbaseline.conf configuration is correct
  ansible.builtin.copy:
    src: zbaseline.conf
    dest: /etc/sysctl.d/zbaseline.conf
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Set sysctl parameters
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: 1
    state: present
 
