- name: Listen for security baseline events from kafka topic
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: kafka.sudo.net
        port: 9092
        topic: security-baseline-events
        verify_mode: CERT_OPTIONAL

  rules:
    - name: debug
      condition: event.message != ""
      action:
        debug:
          msg: “{{ event }}”

    - name: kafka
      condition: event.message != ""
      action:
        run_job:
          name: "apply_security_baseline"
          organization: Default
          extra_vars:
            server_target: "{{ event.host }}"
