- name: Listen for security baseline events from kafka topic
  hosts: all

  sources:
    - ansible.eda.kafka:
        host: kafka.sudo.net
        port: 9092
        topic: security-baseline-events
        verify_mode: CERT_OPTIONAL

  rules:
  rules:
    - name: kafka
      condition: event.body.securitybaseline == "security-baseline was changed"
      action:
        run_job_template:
          name: 'Apply Linux security baseline'
          organization: 'Default'
          filter: '*'
          extra_vars:
            server_target: "{{ event.body.hostname }}"
